<img src="_1bbf5476-5476-461c-9463-5e7e90e40b08.jpeg" style="width: 60%; height: 60%;">

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np   
from sklearn.preprocessing import *
from sklearn.model_selection import *
# import metrics
from sklearn.metrics import *

# Simple modeling

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [5]:
X = df.drop(columns=['species'])
y = df['species']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from xgboost import XGBClassifier

model = XGBClassifier()

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [8]:
y_pred = model.predict(X_test)

In [9]:
accuracy_score(y_test, y_pred)

1.0

In [10]:
# predict a new observation
x = [[6.4, 3.2, 4.5, 1.5]]
a = model.predict(x)

In [11]:
le.inverse_transform(a)

array(['versicolor'], dtype=object)

# Multiple modeling

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [13]:
def all_models(X_train, X_test, y_train, y_test):
    models = {
        'random_forest': RandomForestClassifier(verbose=1),
        'Decision_tree': DecisionTreeClassifier()
    }
    scores =[]
    for name, models in models.items():
        model.fit(X_train, y_train)
        y_pred =model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        scores.append((name, acc))
        df = pd.DataFrame(scores, columns=['name', 'accuracy'])
    return df

In [14]:

all_models(X_train, X_test, y_train, y_test)

            name  accuracy
0  random_forest       1.0
1  Decision_tree       1.0

#   paglon wala kam

<img src="depression-gq-7aug18_istock_b.webp" style="width: 60%; height: 60%;">

In [15]:
def all_models(X_train, X_test, y_train, y_test):
    models = {
        'random_forest': RandomForestClassifier(),
        'Decision_tree': DecisionTreeClassifier()
    }

    # Parameter grids for GridSearchCV
    param_grid = {
        'random_forest': {
            'n_estimators': [50, 100],
            'max_depth': [None, 10],
            'min_samples_split': [2, 5]
        },
        'Decision_tree': {
            'max_depth': [None, 10],
            'min_samples_split': [2, 5]
        }
    }
    
    scores =[]
    for name, models in models.items():

        grid_search = GridSearchCV(models, param_grid[name], cv=5, scoring='accuracy')

        grid_search.fit(X_train, y_train)
        y_pred =grid_search.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        scores.append((name, acc))
        a = print(grid_search.best_params_)
        df = pd.DataFrame(scores, columns=['name', 'accuracy'])  
    return df

In [16]:
all_models(X_train, X_test, y_train, y_test)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.5s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    1.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.8s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.5s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.5s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s

{'max_depth': None, 'min_samples_split': 5, 'n_estimators': 100}
{'max_depth': 10, 'min_samples_split': 2}

(            name  accuracy
 0  random_forest       1.0
 1  Decision_tree       1.0,
 None)

<img src="depression-gq-7aug18_istock_b.webp" style="width: 60%; height: 60%;">

---

# MENTOS Zindagi

<img src="pngtree-a-fashionable-young-man-sitting-in-a-lavish-car-captured-up-close-photo-image_42371614.jpg" style="width: 60%; height: 60%;">

In [17]:
# !pip install optuna

In [19]:
import optuna

In [21]:
def objective(trial):
    # Define the hyperparameters for Randoom Forest
    n_estimators = trial.suggest_int('n_estimators', 50, 100)
    max_depth = trial.suggest_int('max_depth', 10, 50)

    # Create the Random Forest model
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
    )

    # Fit the model
    model.fit(X_train, y_train)

    # Make predictions  
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

# Create a study
study = optuna.create_study(direction='maximize')

# Run the optimization
study.optimize(objective, n_trials=50)
print('-'*50)
print(study.best_params)

[I 2024-07-07 13:30:07,778] A new study created in memory with name: no-name-c237be29-4267-4d7d-87f7-f348c3d40c7f

[I 2024-07-07 13:30:08,109] Trial 0 finished with value: 1.0 and parameters: {'n_estimators': 71, 'max_depth': 48}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:08,280] Trial 1 finished with value: 1.0 and parameters: {'n_estimators': 56, 'max_depth': 13}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:08,512] Trial 2 finished with value: 1.0 and parameters: {'n_estimators': 83, 'max_depth': 47}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:08,662] Trial 3 finished with value: 1.0 and parameters: {'n_estimators': 50, 'max_depth': 26}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:08,891] Trial 4 finished with value: 1.0 and parameters: {'n_estimators': 70, 'max_depth': 21}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:09,191] Trial 5 finished with value: 1.0 and parameters: {'n_estimators': 86, 'max_depth': 27}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:09,431] Trial 6 finished with value: 1.0 and parameters: {'n_estimators': 69, 'max_depth': 38}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:09,721] Trial 7 finished with value: 1.0 and parameters: {'n_estimators': 96, 'max_depth': 10}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:09,939] Trial 8 finished with value: 1.0 and parameters: {'n_estimators': 65, 'max_depth': 14}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:10,129] Trial 9 finished with value: 1.0 and parameters: {'n_estimators': 55, 'max_depth': 43}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:10,423] Trial 10 finished with value: 1.0 and parameters: {'n_estimators': 83, 'max_depth': 35}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:10,653] Trial 11 finished with value: 1.0 and parameters: {'n_estimators': 59, 'max_depth': 50}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:10,861] Trial 12 finished with value: 1.0 and parameters: {'n_estimators': 59, 'max_depth': 19}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:11,122] Trial 13 finished with value: 1.0 and parameters: {'n_estimators': 75, 'max_depth': 34}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:11,348] Trial 14 finished with value: 1.0 and parameters: {'n_estimators': 63, 'max_depth': 42}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:11,763] Trial 15 finished with value: 1.0 and parameters: {'n_estimators': 77, 'max_depth': 20}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:11,963] Trial 16 finished with value: 1.0 and parameters: {'n_estimators': 51, 'max_depth': 30}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:12,292] Trial 17 finished with value: 1.0 and parameters: {'n_estimators': 92, 'max_depth': 10}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:13,094] Trial 18 finished with value: 1.0 and parameters: {'n_estimators': 71, 'max_depth': 16}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:13,493] Trial 19 finished with value: 1.0 and parameters: {'n_estimators': 63, 'max_depth': 24}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:13,925] Trial 20 finished with value: 1.0 and parameters: {'n_estimators': 79, 'max_depth': 31}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:14,217] Trial 21 finished with value: 1.0 and parameters: {'n_estimators': 87, 'max_depth': 50}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:14,486] Trial 22 finished with value: 1.0 and parameters: {'n_estimators': 81, 'max_depth': 46}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:14,811] Trial 23 finished with value: 1.0 and parameters: {'n_estimators': 100, 'max_depth': 46}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:15,109] Trial 24 finished with value: 1.0 and parameters: {'n_estimators': 74, 'max_depth': 39}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:15,532] Trial 25 finished with value: 1.0 and parameters: {'n_estimators': 87, 'max_depth': 46}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:15,970] Trial 26 finished with value: 1.0 and parameters: {'n_estimators': 67, 'max_depth': 42}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:16,446] Trial 27 finished with value: 1.0 and parameters: {'n_estimators': 91, 'max_depth': 39}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:16,791] Trial 28 finished with value: 1.0 and parameters: {'n_estimators': 58, 'max_depth': 48}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:17,427] Trial 29 finished with value: 1.0 and parameters: {'n_estimators': 51, 'max_depth': 24}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:18,427] Trial 30 finished with value: 1.0 and parameters: {'n_estimators': 73, 'max_depth': 35}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:18,807] Trial 31 finished with value: 1.0 and parameters: {'n_estimators': 54, 'max_depth': 15}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:19,127] Trial 32 finished with value: 1.0 and parameters: {'n_estimators': 55, 'max_depth': 32}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:19,607] Trial 33 finished with value: 1.0 and parameters: {'n_estimators': 50, 'max_depth': 28}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:20,295] Trial 34 finished with value: 1.0 and parameters: {'n_estimators': 61, 'max_depth': 24}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:20,637] Trial 35 finished with value: 1.0 and parameters: {'n_estimators': 70, 'max_depth': 18}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:20,823] Trial 36 finished with value: 1.0 and parameters: {'n_estimators': 53, 'max_depth': 12}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:21,095] Trial 37 finished with value: 1.0 and parameters: {'n_estimators': 68, 'max_depth': 22}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:21,496] Trial 38 finished with value: 1.0 and parameters: {'n_estimators': 85, 'max_depth': 27}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:21,931] Trial 39 finished with value: 1.0 and parameters: {'n_estimators': 78, 'max_depth': 43}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:22,112] Trial 40 finished with value: 1.0 and parameters: {'n_estimators': 57, 'max_depth': 36}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:22,331] Trial 41 finished with value: 1.0 and parameters: {'n_estimators': 66, 'max_depth': 17}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:22,720] Trial 42 finished with value: 1.0 and parameters: {'n_estimators': 72, 'max_depth': 27}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:23,392] Trial 43 finished with value: 1.0 and parameters: {'n_estimators': 82, 'max_depth': 21}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:23,668] Trial 44 finished with value: 1.0 and parameters: {'n_estimators': 64, 'max_depth': 11}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:24,049] Trial 45 finished with value: 1.0 and parameters: {'n_estimators': 76, 'max_depth': 14}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:24,347] Trial 46 finished with value: 1.0 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:24,759] Trial 47 finished with value: 1.0 and parameters: {'n_estimators': 62, 'max_depth': 22}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:25,246] Trial 48 finished with value: 1.0 and parameters: {'n_estimators': 56, 'max_depth': 29}. Best is trial 0 with value: 1.0.
[I 2024-07-07 13:30:25,626] Trial 49 finished with value: 1.0 and parameters: {'n_estimators': 60, 'max_depth': 26}. Best is trial 0 with value: 1.0.

--------------------------------------------------
{'n_estimators': 71, 'max_depth': 48}

---

In [ ]:
model =

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

### here explain label encode and OHE and ordinnal encoder

In [23]:
df = sns.load_dataset('titanic')
df.head()

ohe = OneHotEncoder(sparse_output=False)
arr = ohe.fit_transform(df[['class']])
arr

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [25]:
df2 = pd.DataFrame(arr, columns=ohe.get_feature_names_out(['class']))


df2 = pd.DataFrame(arr, columns=ohe.get_feature_names_out(['class']))

In [26]:
df1 = pd.concat([df, df2], axis=1)
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_First,class_Second,class_Third
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.0,0.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0.0,1.0,0.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1.0,0.0,0.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0.0,0.0,1.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1.0,0.0,0.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.0,0.0,1.0

----
## **Swag sa kartain hain ab**

In [ ]:
from sklearn.compose import *

<img src="artworks-000063328833-w8rwc5-t500x500.jpg" style="width: 60%; height: 60%;">

In [ ]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('tip', axis = 1)
y = df['tip']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [27]:
from sklearn.compose import ColumnTransformer

In [ ]:
tr1 = ColumnTransformer(
    transformers = [
        ('OHE', OneHotEncoder(drop='first', sparse_output=True), ['sex', 'time', 'smoker']),
        ('OE', OrdinalEncoder(categories=[['Sun', 'Sat', 'Thur', 'Fri']]), ['day']),
        ('ST', StandardScaler(), ['total_bill'])
    ],
    remainder='passthrough'
)

Scaled_X_train = tr1.fit_transform(X_train)
scaled_X_test = tr1.transform(X_test)

In [ ]:
from flaml import AutoML

In [ ]:
# Initialize and fit the AutoML model
automl = AutoML()

auto_ml_settings = {
    'time_budget': 60,
    'metric': 'r2',
    'task': 'classification',
    'estimator_list': [ 'rf', 'lgbm', 'lgbm_spark', 'lrl1', 'lrl2', 'catboost', 'extra_tree', 'kneighbor',  'histgb']

}

automl.fit(Scaled_X_train, y_train, **auto_ml_settings)

# Evaluate the model
y_pred = automl.predict(scaled_X_test)

[flaml.automl.logger: 07-07 10:58:36] {1680} INFO - task = classification
[flaml.automl.logger: 07-07 10:58:36] {1691} INFO - Evaluation method: cv
[flaml.automl.logger: 07-07 10:58:36] {1789} INFO - Minimizing error metric: 1-r2

Non-spark dataframes only support estimator names not ending with `_spark`. Non-supported estimators are removed.

[flaml.automl.logger: 07-07 10:58:36] {1901} INFO - List of ML learners in AutoML Run: ['rf', 'lgbm', 'lrl1', 'lrl2', 'catboost', 'extra_tree', 'kneighbor', 'histgb']
[flaml.automl.logger: 07-07 10:58:36] {2219} INFO - iteration 0, current learner rf
[flaml.automl.logger: 07-07 10:58:36] {2345} INFO - Estimated sufficient time budget=3499s. Estimated necessary time budget=41s.
[flaml.automl.logger: 07-07 10:58:36] {2392} INFO -  at 0.4s,	estimator rf's best error=0.7519,	best estimator rf's best error=0.7519
[flaml.automl.logger: 07-07 10:58:36] {2219} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 07-07 10:58:37] {2392} INFO -  at 1.2s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 07-07 10:58:37] {2219} INFO - iteration 2, current learner histgb
[flaml.automl.logger: 07-07 10:58:39] {2392} INFO -  at 2.9s,	estimator histgb's best error=0.1789,	best estimator histgb's best error=0.1789
[flaml.automl.logger: 07-07 10:58:39] {2219} INFO - iteration 3, current learner extra_tree
[flaml.automl.logger: 07-07 10:58:39] {2392} INFO -  at 3.2s,	estimator extra_tree's best error=1.5866,	best estimator histgb's best error=0.1789
[flaml.automl.logger: 07-07 10:58:39] {2219} INFO - iteration 4, current learner lgbm
[flaml.automl.logger: 07-07 10:58:40] {2392} INFO -  at 3.8s,	estimator lgbm's best error=0.1792,	best estimator histgb's best error=0.1789
[flaml.automl.logger: 07-07 10:58:40] {2219} INFO - iteration 5, current learner extra_tree
[flaml.automl.logger: 07-07 10:58:40] {2392} INFO -  at 4.0s,	estimator extra_tree's best error=1.5866,	best estimator histgb's best error=0.1789
[flaml.automl.logger: 07-07 10:58:40] {2219} INFO - iteration 6, current learner rf
[flaml.automl.logger: 07-07 10:58:40] {2392} INFO -  at 4.5s,	estimator rf's best error=0.7519,	best estimator histgb's best error=0.1789
[flaml.automl.logger: 07-07 10:58:40] {2219} INFO - iteration 7, current learner lgbm
[flaml.automl.logger: 07-07 10:58:41] {2392} INFO -  at 5.1s,	estimator lgbm's best error=0.0844,	best estimator lgbm's best error=0.0844
[flaml.automl.logger: 07-07 10:58:41] {2219} INFO - iteration 8, current learner rf
[flaml.automl.logger: 07-07 10:58:41] {2392} INFO -  at 5.5s,	estimator rf's best error=0.7519,	best estimator lgbm's best error=0.0844
[flaml.automl.logger: 07-07 10:58:41] {2219} INFO - iteration 9, current learner rf
[flaml.automl.logger: 07-07 10:58:42] {2392} INFO -  at 6.0s,	estimator rf's best error=0.7519,	best estimator lgbm's best error=0.0844
[flaml.automl.logger: 07-07 10:58:42] {2219} INFO - iteration 10, current learner lgbm
[flaml.automl.logger: 07-07 10:58:43] {2392} INFO -  at 6.9s,	estimator lgbm's best error=0.0272,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:43] {2219} INFO - iteration 11, current learner lgbm
[flaml.automl.logger: 07-07 10:58:43] {2392} INFO -  at 7.4s,	estimator lgbm's best error=0.0272,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:43] {2219} INFO - iteration 12, current learner lgbm
[flaml.automl.logger: 07-07 10:58:44] {2392} INFO -  at 8.3s,	estimator lgbm's best error=0.0272,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:44] {2219} INFO - iteration 13, current learner extra_tree
[flaml.automl.logger: 07-07 10:58:44] {2392} INFO -  at 8.6s,	estimator extra_tree's best error=1.5866,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:44] {2219} INFO - iteration 14, current learner lgbm
[flaml.automl.logger: 07-07 10:58:45] {2392} INFO -  at 9.5s,	estimator lgbm's best error=0.0272,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:45] {2219} INFO - iteration 15, current learner extra_tree
[flaml.automl.logger: 07-07 10:58:46] {2392} INFO -  at 10.0s,	estimator extra_tree's best error=1.5866,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:46] {2219} INFO - iteration 16, current learner rf
[flaml.automl.logger: 07-07 10:58:46] {2392} INFO -  at 10.4s,	estimator rf's best error=0.6860,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:46] {2219} INFO - iteration 17, current learner histgb
[flaml.automl.logger: 07-07 10:58:48] {2392} INFO -  at 11.9s,	estimator histgb's best error=0.1789,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:48] {2219} INFO - iteration 18, current learner rf
[flaml.automl.logger: 07-07 10:58:48] {2392} INFO -  at 12.5s,	estimator rf's best error=0.6500,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:48] {2219} INFO - iteration 19, current learner extra_tree
[flaml.automl.logger: 07-07 10:58:49] {2392} INFO -  at 12.9s,	estimator extra_tree's best error=1.4314,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:49] {2219} INFO - iteration 20, current learner lgbm
[flaml.automl.logger: 07-07 10:58:49] {2392} INFO -  at 13.5s,	estimator lgbm's best error=0.0272,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:58:49] {2219} INFO - iteration 21, current learner catboost
[flaml.automl.logger: 07-07 10:59:35] {2392} INFO -  at 59.4s,	estimator catboost's best error=0.1108,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:59:35] {2219} INFO - iteration 22, current learner lrl2
[flaml.automl.logger: 07-07 10:59:39] {2392} INFO -  at 62.8s,	estimator lrl2's best error=0.3402,	best estimator lgbm's best error=0.0272
[flaml.automl.logger: 07-07 10:59:39] {2628} INFO - retrain lgbm for 0.2s
[flaml.automl.logger: 07-07 10:59:39] {2631} INFO - retrained model: LGBMClassifier(colsample_bytree=0.9285002286474459,
               learning_rate=0.7260594590615893, max_bin=511,
               min_child_samples=9, n_estimators=1, n_jobs=-1, num_leaves=4,
               reg_alpha=0.0036840681931986645, reg_lambda=0.7532480505730402,
               verbose=-1)
[flaml.automl.logger: 07-07 10:59:39] {1931} INFO - fit succeeded
[flaml.automl.logger: 07-07 10:59:39] {1932} INFO - Time taken to find the best model: 6.906946420669556

In [ ]:

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')

MAE: 0.8793877551020409

---

In [ ]:
from pycaret.regression import *
from pycaret.classification import *

In [ ]:
df = pd.read_csv('diabetes.csv')
df.head()

,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,32,1
3,89,66,23,94,28.1,0.167,21,0
4,137,40,35,168,43.1,2.288,33,1

In [ ]:
clf = setup(data=df, target='')

---

## Mursaleen

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
cat_cols = df.select_dtypes(include=['object', 'category'])

In [ ]:
cat_cols

        sex embarked   class    who deck  embark_town alive
0      male        S   Third    man  NaN  Southampton    no
1    female        C   First  woman    C    Cherbourg   yes
2    female        S   Third  woman  NaN  Southampton   yes
3    female        S   First  woman    C  Southampton   yes
4      male        S   Third    man  NaN  Southampton    no
..      ...      ...     ...    ...  ...          ...   ...
886    male        S  Second    man  NaN  Southampton    no
887  female        S   First  woman    B  Southampton   yes
888  female        S   Third  woman  NaN  Southampton    no
889    male        C   First    man    C    Cherbourg   yes
890    male        Q   Third    man  NaN   Queenstown    no

[891 rows x 7 columns]

In [ ]:
le = LabelEncoder()
le.fit_transform(cat_cols)